sudo: required
language: java
jdk:
- openjdk11
services:
- docker
script:
- mvn clean install
- ./makekeystore.sh
- |
  export SPA_IMAGE=navikt/spa:$(curl -s https://registry.hub.docker.com/v2/repositories/navikt/spa/tags/ | jq -r '."results"[]["name"]' | sed -n 1p)
  export SPARKEL_IMAGE=navikt/sparkel:$(curl -s https://registry.hub.docker.com/v2/repositories/navikt/sparkel/tags/ | jq -r '."results"[]["name"]' | sed -n 1p)
  export VTPMOCK_IMAGE=navikt/spvtpmock:$(curl -s https://registry.hub.docker.com/v2/repositories/navikt/spvtpmock/tags/ | jq -r '."results"[]["name"]' | sed -n 1p)
- docker-compose rm -f
- docker-compose up --build -d
- pwd
- "./e2e_scripts/wait_for_e2e.sh mvn failsafe:integration-test failsafe:verify"
- docker-compose logs
- docker-compose stop
cache:
  directories:
    - $HOME/.m2
env:
  global:
  - secure: 1+oVWDmZSSIyeRrpos2QO1muNmpEtYgmjYpjg71ZG4O4peBAUsFj91WngLa+7ZWlB3ZrLsSXpsTPlQvzs8kHPxjQtR8MnChOsM3LVzUJMImkxNWQ0pP+sQ3AQAO48bCXPNEN7l9GPCKa2qbzGwoFI3rwNPcH5zFSMrJoBeiyMhIz5UZXAB7mQqSna/0bmjOjHrApjR6nbfpdRlGKNZMuxONQAKKn3Xf6Fr2KH8VwHp33NTfxdxdaVCZtb0sgqraIuDOyEFHaWSUhZ3HcIMaeXJdewJe+1AJab4zSmNhUmSoA/Aqa5hpkP6ICirPk9gbdyyullMubHUvFSO+zCcqNJH7zHoFxfNwPD6LiOrbQPm2Zv8xr9duv09ai+EouAYKo7qeflVOaai8DwSN0wGk0w9uf5Sr1OuOKgkyQAbsNsf18HaNh115Wbrqy/r35bOxYlrg5KGQQCq+D0usrp/QFueWbqsw1bBfssgPA06CcxRElSK694GZhhB1c0C5FYb4rTXAM88eHOK7YyqPcK8VpRY291lc8c6Ae5HBDQR9zu1wnbLhJPTB6a0WZnppUg/sHPgSwqTB08OKhT1085TGU1mzSzfsPmORvt8/pibEqD/jyEMgYWSHm/G7CrHukusVdZRBiwcd/83rbPbgKgZMCZF2PxV3EcFXzQZ8TvnrBtlE=
  - E2E_HOST=localhost:3231
  - GITHUB_APP_ID=19726
notifications:
  slack: false
    #secure: mli/rL3umPd1H88RfX1OTz4eNjzAVD0FdDcfou6bdAiI9bfaq4mid9c3B5gShTkcsiDCe0QimV9syMck2JrdkZ0+CG3HWkbeFz6/UTdNu0Er4pGjedh94gt0btVPhKKINGcU3uOJ99V8QEjwKMm2bVT7n5e0oVdP8sZq/DWfc+aFN7E3WDSbARkduPATqjUdgcxSOBiy2V+Upqll1zGh1uxQPhzOc/2dAe2NcpCh3NfjBU8sIn1YbnqPNDXgVdiuotKkcsp1EV+OUWBPkKj6UP/DzAG9b/j/hmUhb0kMZoJSeRnORiSAqqR3khV6NYU8SaSaiXTbOg1eS7jB21TjNBnJpU82mCOB6wrlBseTPzNNpCvQG/Qjl9Tc0x3YUHbTPIckC0qpVbRpJgliYdSCD2/gqryPf8BZLpE0FchzUi4jZfq/BlTpiruCLQKcyVYHtLRhMXZ28Q9zUpVkjvBQ9ujc5AExhlc5P1jYIewUVhYvWsCdj2SUVu6GJb5jR3kiqBXUxExw8cAq6I+I4sdYigQVk9y5MMVLFyvDNJ91KPBjYdorWltw38L1TK/AjWpFFXnTX7476F5aW4u3ECpLGxwDNkp35TS3zBIpKqAd0wbllYvqK5zBLeCVD3VJgL1LTszstjC15dSamjsoc2xgoN6nliR2YZ29yq2GZUKWZTI=
